"""Deterministic and reversible positive-control faults."""

from .evidence import (
    EvidenceFaultInjection,
    EvidenceFaultKind,
    inject_observed_fallback_kernel,
    inject_reported_backend_mismatch,
    inject_requested_backend_mismatch,
    inject_stride_axis_permutation,
    inject_stride_gap,
    revert_evidence_fault,
)
from .nvfp4 import (
    FaultInjection,
    NVFP4FaultKind,
    first_padding_offset,
    inject_block_scale_reversal,
    inject_global_scale_multiplier,
    inject_nibble_swap,
    inject_padding_corruption,
    inject_scale_index_shift,
    inject_scale_layout_mislabel,
    multiply_global_scale,
    relabel_scale_layout,
    reverse_scale_blocks,
    revert_fault,
    shift_scale_indices,
    swap_packed_nibbles,
    toggle_padding_byte,
)

__all__ = [
    "EvidenceFaultInjection",
    "EvidenceFaultKind",
    "FaultInjection",
    "NVFP4FaultKind",
    "first_padding_offset",
    "inject_block_scale_reversal",
    "inject_global_scale_multiplier",
    "inject_nibble_swap",
    "inject_observed_fallback_kernel",
    "inject_padding_corruption",
    "inject_reported_backend_mismatch",
    "inject_requested_backend_mismatch",
    "inject_scale_index_shift",
    "inject_scale_layout_mislabel",
    "inject_stride_axis_permutation",
    "inject_stride_gap",
    "multiply_global_scale",
    "relabel_scale_layout",
    "reverse_scale_blocks",
    "revert_evidence_fault",
    "revert_fault",
    "shift_scale_indices",
    "swap_packed_nibbles",
    "toggle_padding_byte",
]
